language: python
python:
- '2.7'

before_install:
- openssl aes-256-cbc -K $encrypted_db113545913a_key -iv $encrypted_db113545913a_iv -in id_rsa.enc -out id_rsa -d
- sudo apt-get update -qq
- sudo apt-get install -qq openssh-client

addons:
  ssh_known_hosts: 52.52.169.252

install:
- pip install -r flask_rest_target/requirements.txt
- pip install -r cloud-generic/requirements.txt
- python peachproxy/setup.py -q install
- python pytest-peach/src/setup.py -q install

env:
- PEACH_SSH_HOST=52.52.169.252
  PEACH_SSH_PORT=22
  PEACH_SSH_ID=id_rsa
  PEACH_CONFIG=cloud-generic/peach-web.project
  PEACH_PROFILE=Quick 
  PEACH_UI=http://52.52.169.252:5000 
  PEACH_JUNIT=peach_output.xml
  PEACH_AUTOMATION_CMD="pytest --peach=on pytest-peach/test_target.py" 
  PEACH_VERBOSE=True

before_script:
- python flask_rest_target/rest_target.py

script:
- pytest --junitxml=test.xml pytest-peach/test_target.py
- python cloud-generic/peach_cloud_ci_runner.py
